### ISSUE TITLE
Alignment of the heading with the content

### ISSUE THREAD

**Issue by agarwalaman263** [fossasia/sciencehack.asia#12]
In some of the sections, the heading for the sections is not aligned with the content of the section.
![image](https://user-images.githubusercontent.com/16433241/37230350-3e844b9a-240d-11e8-8296-eb5b4d57d570.png)

**Comment by Puranjay25** [comment]
I want to work on this issue.
In alignment you want the "Hackathons with FOSSASIA" to be placed at centre of the page?

**Comment by mariobehling** [comment]
This is too minor to be regarded as an issue and we rather need people to contribute to software projects. Therefore closing it.
