### ISSUE TITLE
Point twitter to dedicated "sciencehackday" handle instead of "fossasia"

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/sciencehack.asia#6]
The twitter link should point to the dedicated Science Hack Day Handle i.e. [twitter.com/sciencehackday](https://twitter.com/sciencehackday) instead of [twitter.com/fossasia](https://twitter.com/fossasia)

**Comment by deepinder10** [comment]
I have fixed the issue and sent a pull request.
